version: "3.9"
services:
  tipsy-frontend:
    image: tipsy-frontend
    stdin_open: true
    ports:
      - "3000:80"
    networks:
      - public
    restart: unless-stopped
  tipsy-api:
    container_name: express
    image: tipsy-api
    ports:
      - "3001:3001"
    networks:
      - public
      - private
    depends_on:
      - tipsy-db
      - tipsy-db-cache
    restart: unless-stopped
  tipsy-db:
    container_name: mongo
    image: mongo:5.0.8
    ports:
      - "3002:27017"
    networks:
      - private
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  tipsy-db-cache:
    container_name: redis
    image: redis:7.0.0
    ports:
      - "3003:6379"
    networks:
      - private
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  public:
    external: true
  private:
    internal: true
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
